server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:


      routes:
        - id: course
          uri: lb://COURSE
          predicates:
            - Path=/course/**
          filters:
            - AuthenticationFilter


        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**